# Generated by Django 5.2.10 on 2026-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sicav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_transaction",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de transaction"
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de compte",
                    ),
                ),
                (
                    "type_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PEE", "Plan Épargne Entreprise"),
                            ("PER", "Plan Épargne Retraite"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Type (PEE/PER)",
                    ),
                ),
                (
                    "matricule_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Matricule type",
                    ),
                ),
                (
                    "nom_prenom",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nom & Prénom",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("souscription", "Souscription"),
                            ("rachat", "Rachat"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Sens",
                    ),
                ),
                (
                    "nom_fcp",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nom du FCP"
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "cout_moyen_pondere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="Coût moyen pondéré",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction SICAV",
                "verbose_name_plural": "Transactions SICAV",
                "db_table": "sicav",
                "ordering": ["-date_transaction"],
            },
        ),
        migrations.CreateModel(
            name="ValeurLiquidative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "nom_fcp",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nom du FCP"
                    ),
                ),
                (
                    "valeur_liquidative",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                        verbose_name="Valeur liquidative",
                    ),
                ),
                (
                    "est_fcp_islamique",
                    models.BooleanField(
                        default=False, verbose_name="Est FCP islamique"
                    ),
                ),
                (
                    "categorie_fond",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("actions", "Actions"),
                            ("obligations", "Obligations"),
                            ("monetaire", "Monétaire"),
                            ("diversifie", "Diversifié"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Catégorie de fond",
                    ),
                ),
                (
                    "type_fond",
                    models.CharField(
                        blank=True,
                        choices=[("ouvert", "Ouvert"), ("ferme", "Fermé")],
                        max_length=20,
                        null=True,
                        verbose_name="Type de fond",
                    ),
                ),
                (
                    "horizon_investissement",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Horizon d'investissement (années)",
                    ),
                ),
                (
                    "benchmark_obligataire",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Benchmark Obligataire",
                    ),
                ),
                (
                    "benchmark_brvmc",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Benchmark BRVMC",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "depositaire",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Dépositaire",
                    ),
                ),
                (
                    "frais_gestion_ttc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Frais de gestion (TTC de l'actif net / an)",
                    ),
                ),
                (
                    "frais_entree_ttc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Frais d'entrée TTC",
                    ),
                ),
                (
                    "frais_sortie_ttc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Frais de sortie TTC",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur liquidative",
                "verbose_name_plural": "Valeurs liquidatives",
                "db_table": "valeurs_liquidatives",
                "ordering": ["-date"],
            },
        ),
    ]
