# Generated by Django 5.2.10 on 2026-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valeurliquidative",
            name="frais_entree_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Frais d'entrée TTC",
            ),
        ),
        migrations.AlterField(
            model_name="valeurliquidative",
            name="frais_sortie_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="Frais de sortie TTC",
            ),
        ),
    ]
