# Generated by Django 5.2.10 on 2026-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_alter_valeurliquidative_frais_entree_ttc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valeurliquidative",
            name="categorie_fond",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prudent", "Prudent"),
                    ("equilibré", "Équilibré"),
                    ("dynamique", "Dynamique"),
                    ("diversifie", "Diversifié"),
                ],
                max_length=50,
                null=True,
                verbose_name="Catégorie de fond",
            ),
        ),
        migrations.AlterField(
            model_name="valeurliquidative",
            name="frais_entree_ttc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Frais d'entrée TTC"
            ),
        ),
        migrations.AlterField(
            model_name="valeurliquidative",
            name="frais_gestion_ttc",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Frais de gestion (TTC de l'actif net / an)",
            ),
        ),
        migrations.AlterField(
            model_name="valeurliquidative",
            name="frais_sortie_ttc",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Frais de sortie TTC",
            ),
        ),
        migrations.AlterField(
            model_name="valeurliquidative",
            name="type_fond",
            field=models.CharField(
                blank=True,
                choices=[
                    ("actions", "Actions"),
                    ("obligataire", "Obligataire"),
                    ("diversifié", "Diversifié"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type de fond",
            ),
        ),
    ]
