# Generated by Django 5.2.10 on 2026-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_alter_valeurliquidative_categorie_fond_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="valeurliquidative",
            name="echelle_risque",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Échelle de risque (1-7)"
            ),
        ),
    ]
