# Generated by Django 5.2.10 on 2026-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_valeurliquidative_echelle_risque"),
    ]

    operations = [
        migrations.AddField(
            model_name="sicav",
            name="nom_per_pee",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nom du PER/PEE"
            ),
        ),
    ]
