# Generated by Django 5.2.10 on 2026-04-30 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_unify_type_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("login_success", "Connexion reussie"),
                            ("login_failed", "Echec de connexion"),
                            ("logout", "Deconnexion"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit de connexion",
                "verbose_name_plural": "Audits de connexion",
                "db_table": "login_audit",
                "ordering": ["-created_at"],
            },
        ),
    ]
